import os

from src.config.paths import (
    GCS_BRONZE_CHECKPOINT,
    GCS_BRONZE_PATH,
    GCS_GOLD_CHECKPOINT,
    GCS_GOLD_PATH,
    GCS_QUARANTINE_PATH,
    GCS_SILVER_CHECKPOINT,
    GCS_SILVER_PATH,
    LOCAL_BRONZE_CHECKPOINT,
    LOCAL_BRONZE_PATH,
    LOCAL_GOLD_CHECKPOINT,
    LOCAL_GOLD_PATH,
    LOCAL_QUARANTINE_PATH,
    LOCAL_SILVER_CHECKPOINT,
    LOCAL_SILVER_PATH,
)

ENVIRONMENT = os.getenv("ENVIRONMENT", "local")

if ENVIRONMENT == "gcp":
    BRONZE_PATH = GCS_BRONZE_PATH
    SILVER_PATH = GCS_SILVER_PATH
    GOLD_PATH = GCS_GOLD_PATH
    QUARANTINE_PATH = GCS_QUARANTINE_PATH

    BRONZE_CHECKPOINT = GCS_BRONZE_CHECKPOINT
    SILVER_CHECKPOINT = GCS_SILVER_CHECKPOINT
    GOLD_CHECKPOINT = GCS_GOLD_CHECKPOINT

else:
    BRONZE_PATH = LOCAL_BRONZE_PATH
    SILVER_PATH = LOCAL_SILVER_PATH
    GOLD_PATH = LOCAL_GOLD_PATH
    QUARANTINE_PATH = LOCAL_QUARANTINE_PATH

    BRONZE_CHECKPOINT = LOCAL_BRONZE_CHECKPOINT
    SILVER_CHECKPOINT = LOCAL_SILVER_CHECKPOINT
    GOLD_CHECKPOINT = LOCAL_GOLD_CHECKPOINT
