import os

from src.config.paths import (
    GCS_BRONZE_CHECKPOINT,
    GCS_BRONZE_PATH,
    GCS_GOLD_CHECKPOINT,
    GCS_GOLD_PATH,
    GCS_QUARANTINE_PATH,
    GCS_SILVER_CHECKPOINT,
    GCS_SILVER_PATH,
    LOCAL_BRONZE_CHECKPOINT,
    LOCAL_BRONZE_PATH,
    LOCAL_GOLD_CHECKPOINT,
    LOCAL_GOLD_PATH,
    LOCAL_QUARANTINE_PATH,
    LOCAL_SILVER_CHECKPOINT,
    LOCAL_SILVER_PATH,
)

ENVIRONMENT = os.getenv("ENVIRONMENT", "local")

GCP_PROJECT_ID = os.getenv(
    "GCP_PROJECT_ID",
    "real-time-data-platform-507417",
)

GCP_CREDENTIALS = os.getenv(
    "GOOGLE_APPLICATION_CREDENTIALS",
    os.path.join(
        os.path.expanduser("~"),
        ".gcp",
        "real-time-data-platform-sa.json",
    ),
)

BIGQUERY_DATASET = os.getenv(
    "BIGQUERY_DATASET",
    "ecommerce",
)

BIGQUERY_ORDER_SUMMARY_TABLE = os.getenv(
    "BIGQUERY_ORDER_SUMMARY_TABLE",
    "order_summary",
)


if ENVIRONMENT == "gcp":
    BRONZE_PATH = GCS_BRONZE_PATH
    SILVER_PATH = GCS_SILVER_PATH
    GOLD_PATH = GCS_GOLD_PATH
    QUARANTINE_PATH = GCS_QUARANTINE_PATH

    BRONZE_CHECKPOINT = GCS_BRONZE_CHECKPOINT
    SILVER_CHECKPOINT = GCS_SILVER_CHECKPOINT
    GOLD_CHECKPOINT = GCS_GOLD_CHECKPOINT

else:
    BRONZE_PATH = LOCAL_BRONZE_PATH
    SILVER_PATH = LOCAL_SILVER_PATH
    GOLD_PATH = LOCAL_GOLD_PATH
    QUARANTINE_PATH = LOCAL_QUARANTINE_PATH

    BRONZE_CHECKPOINT = LOCAL_BRONZE_CHECKPOINT
    SILVER_CHECKPOINT = LOCAL_SILVER_CHECKPOINT
    GOLD_CHECKPOINT = LOCAL_GOLD_CHECKPOINT